"""Generate YAML deployment manifest from existing Proxmox LXC containers."""

from __future__ import annotations

from datetime import datetime, timezone

import yaml

from .manifest import AuthConfig, ContainerSpec, DeploymentManifest


def extract_container_spec(config: dict, vmid: int) -> ContainerSpec:
    """Convert a Proxmox LXC config dict into a ContainerSpec."""
    # Parse rootfs size
    rootfs = config.get("rootfs", "")
    rootfs_size = "8"
    rootfs_storage = None
    if rootfs:
        parts = rootfs.split(",")
        rootfs_storage = parts[0].split(":")[0]
        for p in parts[1:]:
            if p.startswith("size="):
                rootfs_size = p.split("=")[1].rstrip("GgMm")

    # Collect net interfaces
    net = []
    for i in range(8):
        val = config.get(f"net{i}")
        if val:
            net.append(val)

    # Collect mount points
    mp = []
    for i in range(8):
        val = config.get(f"mp{i}")
        if val:
            mp.append(val)

    # Image: best-effort from ostemplate, otherwise placeholder
    image = config.get("ostemplate") or "CHANGE_ME:latest"

    # Environment variables from lxc config entries
    environment = {}
    for entry in config.get("lxc", []):
        if isinstance(entry, (list, tuple)) and len(entry) >= 2:
            key = entry[0]
            if key.startswith("lxc.environment."):
                env_name = key[len("lxc.environment."):]
                environment[env_name] = str(entry[1])

    return ContainerSpec(
        vmid=vmid,
        image=image,
        hostname=config.get("hostname"),
        memory=int(config.get("memory", 512)),
        swap=int(config.get("swap", 256)),
        cores=int(config.get("cores", 1)),
        rootfs_size=rootfs_size,
        rootfs_storage=rootfs_storage,
        net=net,
        mp=mp,
        privileged=not bool(int(config.get("unprivileged", 1))),
        environment=environment,
    )


def generate_yaml(
    api,
    node: str | None,
    vmids: list[int] | None,
) -> DeploymentManifest:
    """Query Proxmox and build a DeploymentManifest from existing containers."""
    containers = []

    for n in api.nodes.get():
        node_name = n["node"]
        if node and node_name != node:
            continue
        for ct in api.nodes(node_name).lxc.get():
            ct_vmid = int(ct["vmid"])
            if vmids and ct_vmid not in vmids:
                continue
            config = api.nodes(node_name).lxc(ct_vmid).config.get()
            containers.append(extract_container_spec(config, ct_vmid))

    return DeploymentManifest(
        auth=AuthConfig(),
        defaults={},
        containers=containers,
    )


def manifest_to_yaml(manifest: DeploymentManifest) -> str:
    """Serialize a DeploymentManifest to YAML string with header comments."""
    data: dict = {"auth": {"profile": manifest.auth.profile}}

    containers_list = []
    for spec in manifest.containers:
        entry: dict = {"vmid": spec.vmid, "image": spec.image}
        if spec.hostname:
            entry["hostname"] = spec.hostname
        entry["memory"] = spec.memory
        entry["swap"] = spec.swap
        entry["cores"] = spec.cores
        entry["rootfs_size"] = spec.rootfs_size
        if spec.rootfs_storage:
            entry["rootfs_storage"] = spec.rootfs_storage
        if spec.net:
            entry["net"] = spec.net
        if spec.mp:
            entry["mp"] = spec.mp
        if spec.privileged:
            entry["privileged"] = True
        if spec.environment:
            entry["environment"] = spec.environment
        containers_list.append(entry)

    data["containers"] = containers_list

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = (
        f"# Generated by pve-oci generate on {timestamp}\n"
        "# Review 'image' fields - Proxmox may not store the original OCI reference.\n\n"
    )
    return header + yaml.dump(data, default_flow_style=False, sort_keys=False)
